# Generated by Django 5.0.2 on 2024-02-14 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="rating",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(5)]
            ),
        ),
    ]
