# Generated by Django 5.0.2 on 2024-02-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_booking_experience_alter_booking_room_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="check_out",
            field=models.DateField(blank=True, null=True),
        ),
    ]
