# Generated by Django 5.0.2 on 2024-02-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_booking_check_out"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="experience_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="experience_start",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
